app = "vinodhini-software-api"

[build]
  go_mod_path = "."

[env]
  SERVER_PORT = "8080"
  SERVER_HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
